Repository dogtagpki/jss, pull requests merged in 2018-10, with the labels that each got.

#40 Make test scripts exit on first error
  tools/test_perl_style.sh
  tools/test_shell_style.sh
Labels: ci

#38 Document branches in upstream [skip ci]
  README.md
  docs/repo_archive.md
Labels: docs

#42 Add -notimestamp option to javadoc creation
  build_java.pl
Labels: bug, build, docs

#39 Fix docstring for org.mozilla.jss.pkix.cms.SignedData
  org/mozilla/jss/pkix/cms/SignedData.java
Labels: bug, docs

#44 Create script to automatically detect exports for build
  tools/autoenv.sh
  tools/test_shell_style.sh
Labels: build, enhancement

#45 Add tool to run container images
  .travis.yml
  tools/run_container.sh
  tools/test_shell_style.sh
Labels: ci, enhancement

#51 Fix Travis CI on v4.4.x branch
  .travis.yml
Labels: blocker, bug, ci

#52 Fix truncation warning
  coreconf/nsinstall/pathsub.c
Labels: backport, minor

#53 Fix warning: assignment discards ‘const’ qualifier from pointer targe…
  org/mozilla/jss/pkcs11/PK11Store.c
  org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.c
Labels: backport, minor

#50 Fix docstring for org.mozilla.jss.pkix.cms.SignedData
  org/mozilla/jss/pkix/cms/SignedData.java
Labels: backport, bug, docs, minor

#54 Add dependency on JAXB for JDK9+
  README.md
  jss.spec
  lib/Common.pm
  tools/Dockerfiles/ubuntu_jdk8
  tools/autoenv.sh
Labels: blocker, build, jdk9+

#56 Add additional Fedora testing images
  .travis.yml
  tools/Dockerfiles/fedora_29
  tools/Dockerfiles/fedora_29_jdk11
  tools/Dockerfiles/fedora_rawhide
Labels: ci, fedora

#59 Fix problem where firefox could not display the INDEX tab as of jdk 11
  build_java.pl
  overview.html
Labels: docs, jdk9+, regen-gh-pages

#62 Documentation update
  build_java.pl
  overview.html
  tools/javadoc/overview.html
Labels: docs, regen-gh-pages

#68 Fedora 29 was released!
  .travis.yml
Labels: ci, fedora
