Repository dogtagpki/jss, pull requests merged in 2018-11, with the labels that each got.

#66 Fix javadoc reported errors when switching to jdk11
  org/mozilla/jss/CryptoManager.java
  org/mozilla/jss/InitializationValues.java
  org/mozilla/jss/SecretDecoderRing/KeyManager.java
  org/mozilla/jss/asn1/BIT_STRING.java
  org/mozilla/jss/crypto/Algorithm.java
  org/mozilla/jss/crypto/KeyPairGenerator.java
  org/mozilla/jss/netscape/security/pkcs/PKCS7.java
  org/mozilla/jss/netscape/security/provider/DSA.java
  org/mozilla/jss/pkix/cert/CertificateInfo.java
  org/mozilla/jss/pkix/cmc/RevokeRequest.java
  org/mozilla/jss/pkix/cmmf/RevRequest.java
  org/mozilla/jss/ssl/SSLServerSocket.java
  org/mozilla/jss/ssl/SSLSocket.java
  org/mozilla/jss/ssl/SSLSocketException.java
  org/mozilla/jss/ssl/SocketBase.java
Labels: docs, jdk9+, minor, regen-gh-pages

#67 Sync JSS with NSS's TLS cipher suite lists
  org/mozilla/jss/ssl/SSLCipher.java
  org/mozilla/jss/ssl/SSLSocket.java
  org/mozilla/jss/tests/Constants.java
Labels: enhancement, regen-gh-pages

#71 Small script fixes
  tools/autoenv.sh
  tools/build_pkcs11_constants.py
Labels: bug, ci, minor

#73 Replace instances of loser label with finish
  org/mozilla/jss/CryptoManager.c
  org/mozilla/jss/PK11Finder.c
  org/mozilla/jss/pkcs11/PK11SecureRandom.c
  org/mozilla/jss/pkcs11/PK11SymmetricKeyDeriver.c
  org/mozilla/jss/ssl/callbacks.c
Labels: bug, enhancement

#76 Remove unused JNI for NativeProxy
  org/mozilla/jss/util/NativeProxy.c
  org/mozilla/jss/util/NativeProxy.h
Labels: build, minor

#77 Remove unused class KeyFactorySpi1_4
  org/mozilla/jss/provider/java/security/KeyFactorySpi1_4.java
Labels: build, minor

#82 Simplify version handling
  lib/jss.def
  lib/manifest.mn
  manifest.mn
  org/mozilla/jss/CryptoManager.c
  org/mozilla/jss/CryptoManager.java
  org/mozilla/jss/JSSProvider.java
  org/mozilla/jss/tests/JSSPackageTest.java
  org/mozilla/jss/util/jssver.h
Labels: blocker, build, enhancement

#83 Add lib/MANIFEST.MF.in and lib/jss.map
  lib/MANIFEST.MF.in
  lib/jss.map
Labels: blocker, build, enhancement, minor

#86 Add ClientAuth tests to ctest
  cmake/JSSConfig.cmake
  cmake/JSSTests.cmake
Labels: blocked, build, enhancement, minor

#88 Refactor CMake to support building other C targets
  cmake/JSSCommon.cmake
  cmake/JSSConfig.cmake
Labels: build, enhancement

#90 Add build directory
  build/.gitkeep
Labels: build, minor

#91 Update docs/pkcs11constants.md according to new build system
  docs/pkcs11_constants.md
Labels: docs, minor

#92 Bump keysizes to 4096
  org/mozilla/jss/tests/GenerateTestCert.java
  org/mozilla/jss/tests/SSLClientAuth.java
  org/mozilla/jss/tests/X509CertTest.java
Labels: blocker, bug, build

#94 Reintroduce PKCS11 Constants test
  cmake/JSSTests.cmake
Labels: build, jdk9+, minor

#95 Allow tests to be run repeatedly
  cmake/JSSConfig.cmake
  cmake/JSSTests.cmake
Labels: build, enhancement

#96 Add TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 to tests
  org/mozilla/jss/tests/Constants.java
Labels: bug, build

#98 Separate test artifacts
  cmake/JSSCommon.cmake
  cmake/JSSConfig.cmake
Labels: blocker, build, enhancement, regen-gh-pages

#99 Library testing
  cmake/JSSCommon.cmake
  cmake/JSSConfig.cmake
  cmake/JSSTests.cmake
Labels: blocked, build, javax

#100 Enable release builds
  CMakeLists.txt
  cmake/JSSCommon.cmake
  cmake/JSSConfig.cmake
Labels: blocked, build, critical

#102 Release JSS version 4.5.1
  cmake/JSSConfig.cmake
  jss.spec
Labels: release
