Repository dogtagpki/jss, pull requests merged in 2019-03, with the labels that each got.

#133 Added Cert.sortCertificateChain()
  jss.spec
  org/mozilla/jss/netscape/security/util/Cert.java
Labels: enhancement

#135 Remove needless dependency on hamcrest
  README.md
  docs/dependencies.md
  jss.spec
  tools/Dockerfiles/debian_jdk11
  tools/Dockerfiles/fedora_29_jdk11
  tools/Dockerfiles/fedora_rawhide
  tools/Dockerfiles/ubuntu_jdk8
Labels: bug, ci

#137 Added ChainSortingTest
  .classpath
  cmake/JSSTests.cmake
  org/mozilla/jss/netscape/security/util/Cert.java
  org/mozilla/jss/tests/ChainSortingTest.java
Labels: ci, enhancement

#139 Release JSS v4.4.5
  jss.spec.in
  org/mozilla/jss/CryptoManager.java
  org/mozilla/jss/JSSProvider.java
  org/mozilla/jss/util/jssver.h
Labels: release

#140 Align upstream and downstream spec files
  build.sh
  jss.spec.in
Labels: bug, build

#141 Fix release procedure in jss.spec
  jss.spec
Labels: build, docs

#143 Branch to v4.6.x
  cmake/JSSConfig.cmake
  jss.spec
Labels: release

#144 Fix IRC channel name: #dogtag-pki
  README.md
  docs/contributing.md
Labels: bug, regen-gh-pages

#148 Remove 3s sleep from SetupDBs
  org/mozilla/jss/tests/SetupDBs.java
Labels: ci, minor

#149 Use --with-timestamp and --with-commit-id for COPR
  .copr/Makefile
Labels: build, fedora
