Repository dogtagpki/jss, pull requests merged in 2019-06, with the labels that each got.

#164 Add tests for JSSProvider - 5:3
  cmake/JSSTests.cmake
  org/mozilla/jss/tests/JSSProvider.java
Labels: blocked, ci, javax

#194 Expose SSL_{REQUEST,REQUIRE}_CERTIFICATE constants
  lib/jss.map
  org/mozilla/jss/nss/SSL.c
  org/mozilla/jss/nss/SSL.java
Labels: blocker, bug, javax

#195 Fix some trivial deprecation warnings #33
  org/mozilla/jss/asn1/ASN1Header.java
  org/mozilla/jss/asn1/OBJECT_IDENTIFIER.java
  org/mozilla/jss/asn1/SET.java
  org/mozilla/jss/ssl/SSLClient.java
  org/mozilla/jss/ssl/SSLTest.java
  org/mozilla/jss/ssl/SSLVersionRange.java
  org/mozilla/jss/tests/JSSE_SSLClient.java
  org/mozilla/jss/tests/JSS_SelfServServer.java
  org/mozilla/jss/util/NativeProxy.java
Labels: bug, jdk9+, minor

#198 Add ssl.javax.JSSParameters
  org/mozilla/jss/ssl/javax/JSSParameters.java
Labels: blocker, enhancement, javax, regen-gh-pages

#200 Store cert alias in JSSParameters
  org/mozilla/jss/ssl/javax/JSSParameters.java
Labels: enhancement, javax

#201 Update javadocs from master at 2019-06-10 10:22
  master/javadocs/allclasses-frame.html
  master/javadocs/allclasses-noframe.html
  master/javadocs/index-all.html
  master/javadocs/org/mozilla/jss/netscape/security/extensions/PresenceServerExtension.html
  master/javadocs/org/mozilla/jss/nss/Buffer.html
  master/javadocs/org/mozilla/jss/nss/SSL.html
  master/javadocs/org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/JSSKeyManager.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/JSSKeyManagerFactory.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/JSSTrustManagerFactory.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/package-frame.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/package-summary.html
  master/javadocs/org/mozilla/jss/provider/javax/crypto/package-tree.html
  master/javadocs/org/mozilla/jss/ssl/SSLVersionRange.html
  master/javadocs/overview-tree.html
  v4.5.x/javadocs/deprecated-list.html
Labels: docs

#202 Add org.mozilla.jss.ssl.javax to javadoc generation
  cmake/JSSConfig.cmake
Labels: build, docs

#203 Update PKCS11Constants
  org/mozilla/jss/pkcs11/PKCS11Constants.java
Labels: enhancement, primitives

#197 Fix additional trivial deprecation warnings #34
  org/mozilla/jss/netscape/security/pkcs/PKCS8Key.java
  org/mozilla/jss/netscape/security/util/ObjectIdentifier.java
  org/mozilla/jss/netscape/security/x509/IPAddressName.java
  org/mozilla/jss/netscape/security/x509/X509Key.java
Labels: jdk9+, minor

#204 Update javadocs from master at 2019-06-10 10:44
  master/javadocs/allclasses-frame.html
  master/javadocs/allclasses-noframe.html
  master/javadocs/constant-values.html
  master/javadocs/index-all.html
  master/javadocs/org/mozilla/jss/netscape/security/extensions/PresenceServerExtension.html
  master/javadocs/org/mozilla/jss/netscape/security/x509/CertificateExtensions.html
  master/javadocs/org/mozilla/jss/netscape/security/x509/Extensions.html
  master/javadocs/org/mozilla/jss/pkcs11/PKCS11Constants.html
  master/javadocs/org/mozilla/jss/ssl/javax/JSSParameters.html
  master/javadocs/org/mozilla/jss/ssl/javax/package-frame.html
  master/javadocs/org/mozilla/jss/ssl/javax/package-summary.html
  master/javadocs/org/mozilla/jss/ssl/javax/package-tree.html
  master/javadocs/org/mozilla/jss/ssl/package-summary.html
  master/javadocs/org/mozilla/jss/ssl/package-tree.html
  master/javadocs/org/mozilla/jss/util/package-summary.html
  master/javadocs/org/mozilla/jss/util/package-tree.html
  master/javadocs/overview-frame.html
  master/javadocs/overview-summary.html
  master/javadocs/overview-tree.html
  master/javadocs/package-list
Labels: docs

#206 Test SSL handshake without TCP model
  org/mozilla/jss/tests/TestBufferPRFD.java
Labels: ci, javax, minor

#205 [nss.PR] Create BufferPRFD when peer_info is null
  org/mozilla/jss/nss/PR.c
Labels: bug, critical, javax

#208 Track server hostname in JSSParameters
  org/mozilla/jss/ssl/javax/JSSParameters.java
Labels: enhancement, javax, minor

#209 Support LD_FLAGS from environment
  cmake/JSSConfig.cmake
Labels: bug, build

#210 Add additional error handling functions
  lib/jss.map
  org/mozilla/jss/nss/PR.c
  org/mozilla/jss/nss/PR.java
  org/mozilla/jss/tests/TestPRFD.java
Labels: enhancement

#211 Wrap SSL_ConfigServerCert
  cmake/JSSTests.cmake
  lib/jss.map
  org/mozilla/jss/nss/SSL.c
  org/mozilla/jss/nss/SSL.java
  org/mozilla/jss/tests/TestBufferPRFD.c
  org/mozilla/jss/tests/TestBufferPRFD.java
Labels: enhancement, javax, protocols

#212 Return String in jss.nss.PR error text functions
  lib/jss.map
  org/mozilla/jss/nss/PR.c
  org/mozilla/jss/nss/PR.java
  org/mozilla/jss/tests/TestPRFD.java
Labels: enhancement, javax

#213 Switch to SSL_ConfigServerCert
  org/mozilla/jss/ssl/SSLServerSocket.c
Labels: enhancement, javax
