Repository dogtagpki/jss, pull requests merged in 2019-08, with the labels that each got.

#225 fix typo in JUnit CMake variable
  cmake/JSSConfig.cmake
Labels: bug, build, minor

#227 fix typo in JUnit CMake variable
  cmake/JSSConfig.cmake
Labels: backport, bug, build, minor

#228 Add a few standard Java interfaces when possible
  org/mozilla/jss/crypto/Cipher.java
  org/mozilla/jss/crypto/SymmetricKey.java
  org/mozilla/jss/pkcs11/PK11Key.java
  org/mozilla/jss/pkcs11/PK11SymKey.java
Labels: javax

#231 Add exit(1) in failure case of TestBufferPRFD
  org/mozilla/jss/tests/TestBufferPRFD.c
Labels: bug, build

#232 Increase size of async io buffer in TestBufferPRFD
  org/mozilla/jss/tests/TestBufferPRFD.c
Labels: bug, protocols

#235 Add CHECK_DEPRECATION CMake option
  CMakeLists.txt
Labels: build, enhancement

#199 Fix jss internal deprecation warnings #35
  org/mozilla/jss/pkcs7/EncryptedContentInfo.java
  org/mozilla/jss/pkix/cms/EncryptedContentInfo.java
  org/mozilla/jss/pkix/primitive/EncryptedPrivateKeyInfo.java
Labels: jdk9+

#238 Move buffer.{c,h} -> j_buffer.{c,h}
  org/mozilla/jss/nss/Buffer.c
  org/mozilla/jss/nss/Buffer.java
  org/mozilla/jss/nss/BufferProxy.h
  org/mozilla/jss/ssl/javax/BufferPRFD.c
  org/mozilla/jss/ssl/javax/BufferPRFD.h
  org/mozilla/jss/ssl/javax/j_buffer.c
  org/mozilla/jss/ssl/javax/j_buffer.h
  org/mozilla/jss/tests/buffer_size_1.c
  org/mozilla/jss/tests/buffer_size_4.c
Labels: bug, build

#233 Support ECGenParameterSpec in PK11KeyPairGenerator
  org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
  org/mozilla/jss/util/ECCurve.java
Labels: enhancement, javax, primitives
