Repository dogtagpki/jss, pull requests merged in 2019-07, with the labels that each got.

#215 Terminate SSL test cases after too many attempts
  org/mozilla/jss/tests/TestBufferPRFD.c
  org/mozilla/jss/tests/TestBufferPRFD.java
Labels: bug, ci, minor

#216 Added uncleared password warning
  org/mozilla/jss/util/Password.java
Labels: enhancement

#217 Fixing uncleared password in MacData
  org/mozilla/jss/pkcs12/MacData.java
Labels: bug, minor

#219 Add alternative HMAC names for JSSProvider
  org/mozilla/jss/JSSProvider.java
Labels: enhancement, minor, protocols

#221 Rename HMACTest -> CrossHMACTest
  cmake/JSSTests.cmake
  org/mozilla/jss/tests/CrossHMACTest.java
Labels: bug, minor

#220 Remove tests/all.pl - old test suite runner
  org/mozilla/jss/tests/all.pl
Labels: build, minor, question

#222 Fix SHA1-HMAC in SymmetricKey
  org/mozilla/jss/crypto/KeyGenAlgorithm.java
  org/mozilla/jss/crypto/SymmetricKey.java
Labels: blocker, bug, primitives

#223 Add SHA2 HMAC
  org/mozilla/jss/crypto/Algorithm.c
  org/mozilla/jss/crypto/Algorithm.h
  org/mozilla/jss/crypto/Algorithm.java
  org/mozilla/jss/crypto/KeyGenAlgorithm.java
  org/mozilla/jss/crypto/SymmetricKey.java
Labels: blocked, primitives
