Repository dogtagpki/jss, pull requests merged in 2019-01, with the labels that each got.

#108 Bump version number to v4.5.2
  cmake/JSSConfig.cmake
  jss.spec
Labels: release

#109 Add fromOID to KeyWrapAlgorithm
  org/mozilla/jss/crypto/KeyWrapAlgorithm.java
Labels: backport

#111 Add -notimestamp option to javadoc creation
  build_java.pl
Labels: backport

#113 Backport - Bump keysizes to 4096
  org/mozilla/jss/tests/GenerateTestCert.java
  org/mozilla/jss/tests/SSLClientAuth.java
  org/mozilla/jss/tests/X509CertTest.java
Labels: backport

#112 Backport - Add org.mozilla.jss.pkcs11.PKCS11Constants
  org/mozilla/jss/pkcs11/PKCS11Constants.java
Labels: backport

#115 Fix LDAPJDK circular dependency
  .classpath
  build_java.pl
  jss.spec.in
Labels: backport, bug, build, critical

#116 Disable x25519 in FIPS mode
  org/mozilla/jss/CryptoManager.c
  org/mozilla/jss/CryptoManager.java
Labels: bug

#118 `make check` -> `make test` in README.md
  README.md
Labels: docs, minor

#120 Add exec method to execute shell commands with input
  org/mozilla/jss/netscape/security/util/Utils.java
Labels: bug
