Repository dogtagpki/jss, pull requests merged in 2020-04, with the labels that each got.

#444 Prevent post-handshake configuration changes
  org/mozilla/jss/ssl/javax/JSSEngine.java
Labels: bug, javax

#460 JSSContext: Default Parameters
  org/mozilla/jss/provider/javax/net/JSSContextSpi.java
  org/mozilla/jss/ssl/javax/JSSEngine.java
Labels: enhancement, javax

#463 Add optional CI to check if PKI build is broken
  .github/workflows/optional.yml
  tools/Dockerfiles/pki_build
Labels: ci, enhancement

#465 Add unchecked exceptions to debug build tests
  cmake/JSSConfig.cmake
  org/mozilla/jss/ssl/SSLAlertDescription.java
  tools/Dockerfiles/fedora_rawhide
Labels: bug, build, ci, minor

#470 Release JSS v4.4.9
  jss.spec.in
  org/mozilla/jss/CryptoManager.java
  org/mozilla/jss/JSSProvider.java
  org/mozilla/jss/util/jssver.h
Labels: release

#472 Add test for GlobalRefProxy
  cmake/JSSTests.cmake
  lib/jss.map
  org/mozilla/jss/tests/TestGlobalReference.java
  org/mozilla/jss/util/GlobalRefProxy.c
  org/mozilla/jss/util/GlobalRefProxy.java
Labels: ci

#476 Move from _NETSCAPE_ to _NSS_ PKCS#11 constants
  org/mozilla/jss/pkcs11/PK11SymKey.c
Labels: build, minor

#480 Branch to v4.7.0 beta release 1
  cmake/JSSConfig.cmake
  jss.spec
Labels: enhancement

#486 Fix latest jss.map entry to v4.7.0
  lib/jss.map
Labels: bug, minor

#481 Accept NULL in CryptoManager.setPasswordCallback()
  org/mozilla/jss/CryptoManager.c
Labels: bug, minor

#490 Allow NULL PK11PrivKey identifiers
  org/mozilla/jss/pkcs11/PK11PrivKey.c
Labels: bug

#484 Remove space from AlgorithmId.toString()
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug

#485 Remove space from AlgorithmId.toString()
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: backport, bug

#497 Enable GitHub Actions on v4.6.x
  .github/workflows/optional.yml
  .github/workflows/required.yml
Labels: ci

#499 Fix NPE in Utils.HexEncode
  org/mozilla/jss/netscape/security/util/Utils.java
Labels: bug, ci, minor

#503 Minor improvement to GH actions
  .github/workflows/optional.yml
  .github/workflows/required.yml
Labels: ci, refactor

#504 Fix SHA512withRSA/PSS identifier
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug

#506 Fix SHA512withRSA/PSS identifier
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug

#507 Consume all input bytes in logging sockets
  org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
Labels: bug, javax, minor

#508 Enable debug logging with run_test.sh
  tools/run_test.sh.in
Labels: ci

#509 Add AlgorithmId.toStringWithParams, fix toString
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: backport, bug

#510 Add AlgorithmId.toStringWithParams, fix toString
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug

#513 Release JSS v4.6.4
  cmake/JSSConfig.cmake
  jss.spec
Labels: release

#512 Comply with crypto-policies outside of Tomcat
  org/mozilla/jss/crypto/Policy.java
  org/mozilla/jss/ssl/SSLVersionRange.java
  org/mozilla/jss/ssl/javax/JSSEngine.java
Labels: enhancement, javax

#517 Use non-interactive apt installation
  tools/Dockerfiles/debian_jdk11
  tools/Dockerfiles/ubuntu_jdk8
Labels: bug, ci

#518 Always run workflows regardless of branch
  .github/workflows/optional.yml
  .github/workflows/required.yml
Labels: ci

#520 Added PKCS7 constructor
  org/mozilla/jss/netscape/security/pkcs/PKCS7.java
  org/mozilla/jss/netscape/security/x509/CertificateChain.java
Labels: enhancement, minor

#522 Added CertificateChain.sort()
  org/mozilla/jss/netscape/security/x509/CertificateChain.java
  org/mozilla/jss/tests/CertificateChainTest.java
Labels: enhancement

#524 Handle premature JSSEngine.cleanup()
  org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
Labels: bug, javax

#527 Fixed CertificateChainTest.testGetterMethods()
  org/mozilla/jss/tests/CertificateChainTest.java
Labels: bug, ci

#528 Move JDK11 test to required section
  .github/workflows/optional.yml
  .github/workflows/required.yml
Labels: ci

#533 Hack: provide SSLContext's SSLSocket via SunJSSE
  org/mozilla/jss/provider/javax/net/JSSContextSpi.java
Labels: bug, javax
