Repository dogtagpki/jss, pull requests merged in 2020-05, with the labels that each got.

#535 JSSEngine: Add getSSLParameters
  org/mozilla/jss/ssl/javax/JSSEngine.java
Labels: blocked, blocker, enhancement, javax

#537 Remove JSSContextSpi for the time being
  org/mozilla/jss/JSSLoader.java
  org/mozilla/jss/JSSProvider.java
  org/mozilla/jss/tests/TestSSLEngine.java
  tools/jss.cfg.in
Labels: critical

#541 More SHA256withRSA/PSS algorithm fixes.
  org/mozilla/jss/crypto/SignatureAlgorithm.java
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug

#542 Switch to using %license macro
  jss.spec
Labels: fedora

#543 Fix RSA/PSS with SHA-512 signature algorithm
  org/mozilla/jss/crypto/SignatureAlgorithm.java
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Labels: bug, primitives

#546 SSLSocket: detect failure to recieve CLOSE_NOTIFY
  org/mozilla/jss/ssl/javax/JSSSocketChannel.java
Labels: bug, critical, javax

#549 Simplify JSSServerSocketChannel.accept()
  org/mozilla/jss/ssl/javax/JSSServerSocketChannel.java
Labels: javax, refactor

#557 Enable JSS-Provided SSLEngine
  org/mozilla/jss/JSSProvider.java
Labels: javax

#560 Related: Bug 1710105 - JSS: add RSA PSS support
  org/mozilla/jss/netscape/security/util/Cert.java
Labels: bug, minor

#563 Related: Bug 1710105 - JSS: add RSA PSS support
  org/mozilla/jss/netscape/security/util/Cert.java
Labels: backport

#558 Add SSLSocket benchmark
  docs/usage/benchmarksslsocket.md
  org/mozilla/jss/tests/BenchmarkSSLSocket.java
Labels: enhancement, javax, protocols

#566 Allow URL-safe Base64 decoding
  cmake/JSSTests.cmake
  org/mozilla/jss/netscape/security/util/Utils.java
  org/mozilla/jss/tests/Base64Parsing.java
Labels: bug, critical

#567 Allow URL-safe Base64 decoding
  cmake/JSSTests.cmake
  org/mozilla/jss/netscape/security/util/Utils.java
  org/mozilla/jss/tests/Base64Parsing.java
Labels: backport, bug, critical
