Repository dogtagpki/jss, pull requests merged in 2020-03, with the labels that each got.

#419 Query and Set Default SSL configuration
  org/mozilla/jss/nss/SSL.c
  org/mozilla/jss/nss/SSL.java
  org/mozilla/jss/ssl/SSLProtocolVariant.java
Labels: javax

#422 Move CryptoManager logging to debug
  org/mozilla/jss/CryptoManager.java
Labels: enhancement

#413 Remove deprecated netscape.security.acl
  org/mozilla/jss/netscape/security/acl/AclEntryImpl.java
  org/mozilla/jss/netscape/security/acl/AclImpl.java
  org/mozilla/jss/netscape/security/acl/AllPermissionsImpl.java
  org/mozilla/jss/netscape/security/acl/GroupImpl.java
  org/mozilla/jss/netscape/security/acl/OwnerImpl.java
  org/mozilla/jss/netscape/security/acl/PermissionImpl.java
  org/mozilla/jss/netscape/security/acl/PrincipalImpl.java
  org/mozilla/jss/netscape/security/acl/WorldGroupImpl.java
Labels: enhancement

#425 Detect NSS with broken CMACs during configuration
  cmake/JSSConfig.cmake
  tools/tests/cmac.c
Labels: build, enhancement

#429 Add diff to pkcs11check installation list
  tools/Dockerfiles/pkcs11check
Labels: bug, ci

#430 Remove token key checks
  org/mozilla/jss/pkcs11/PK11Cipher.java
  org/mozilla/jss/pkcs11/PK11KeyWrapper.java
  org/mozilla/jss/pkcs11/PK11MessageDigest.java
Labels: blocked, bug

#435 Move to proper feature checks
  .gitignore
  CMakeLists.txt
  cmake/JSSConfig.cmake
  org/mozilla/jss/jssconfig.h.in
  org/mozilla/jss/ssl/SSLCipher.c
Labels: build, enhancement

#438 Update PKCS11Constants from NSS v3.50
  org/mozilla/jss/pkcs11/PKCS11Constants.java
Labels: enhancement, primitives

#440 Add feature detection for SSLCipherInfo.peerDelegCred
  cmake/JSSConfig.cmake
  org/mozilla/jss/jssconfig.h.in
  org/mozilla/jss/nss/SSL.c
  org/mozilla/jss/nss/SSLChannelInfo.java
  org/mozilla/jss/util/java_ids.h
Labels: bug, primitives

#448 Add zip, unzip to BuildRequires
  jss.spec
Labels: build, minor

#445 JSS RSA-PSS support first cut.
  org/mozilla/jss/JSSProvider.java
  org/mozilla/jss/crypto/Algorithm.c
  org/mozilla/jss/crypto/Algorithm.h
  org/mozilla/jss/crypto/Algorithm.java
  org/mozilla/jss/crypto/SignatureAlgorithm.java
  org/mozilla/jss/netscape/security/x509/AlgorithmId.java
  org/mozilla/jss/pkcs11/KeyType.java
  org/mozilla/jss/pkcs11/PK11Signature.c
  org/mozilla/jss/pkcs11/PK11Signature.java
  org/mozilla/jss/pkcs11/pk11util.h
  org/mozilla/jss/provider/java/security/JSSSignatureSpi.java
  org/mozilla/jss/provider/java/security/RSAPSSAlgorithmParameters.java
  org/mozilla/jss/tests/JCASigTest.java
  org/mozilla/jss/tests/SigTest.java
  org/mozilla/jss/tests/all.pl
  org/mozilla/jss/util/java_ids.h
Labels: bug, enhancement, needs review, primitives
